languageCode = "en-us"
baseURL = "https://vilgefortz.art/"
theme = "terminal"
relativeURLs = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.90.0"

[params]
  centerTheme = true
  custom_css = ["css/style.css"]
  readingTime = true
  summaryLength = 70
  integrity = ""

  [[params.social-links]]
    name = "Twitter"
    url = "https://twitter.com/mhmrth1"

  [[params.social-links]]
    name = "GitHub"
    url = "https://github.com/Krak9n"
